# 配置端口
server:
  port: 60028
  #全局配置接口地址前缀
  servlet:
    context-path: /api/woa
# 资源路径
path:

  upload: D:/import/orderPicture/
  file: D:/import/orderPicture/

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.201:3306/street_light?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
    username: root
    password: Exc_led1
    type: com.alibaba.druid.pool.DruidDataSource
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #去掉控制台打印版本号
    banner: false
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  # 指定需要使用的日志配置文件名称
  config: classpath:logback-dev.xml
http:
  # 位置管理
  dlm:
    url: http://192.168.0.29:60027
    getLampPost: /api/dlm/sl/lamp/post
    getStreetByAreaIdList: /api/dlm/location/street/by/area
    getSiteByStreetIdList: /api/dlm/location/site/by/street
    getLampPostByIdList: /api/dlm/sl/lamp/post/get/list
    getLampPostBySiteIdList: /api/dlm/sl/lamp/post/by/site
    getLampPostByGroupIdList: /api/dlm/sl/lamp/post/by/group
  ua:
    url: http://192.168.0.252:60029
    selectName: /api/ua/user/name/by/ids
    selectById: /api/ua/user
    getApproval: /api/ua/user/manager/id
  occ:
    url: http://192.168.0.254:60025
    #APP，我的消息批量更改为已读
    newsStatus: /api/occ/ah/play/news/status
    #APP，我的消息全部更改为已读
    newsAll: /api/occ/ah/play/news/all

#认证中心
security:
  authe:
    url: http://192.168.0.252:60029/api/ua/authe
  authc:
    url: http://192.168.0.252:60029/api/ua/authc

#不需要认证
exclude:
  authe:
    url: /api/test,/orderPicture/**,/error

  #不需要鉴权
  authc:
    url: /api/test,/orderPicture/**,/error