# 配置端口
server:
  port: 60027
# 资源路径
path:
  upload: D:/import/
  file: D:/import/static
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.111.89:3306/street_light?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://193.112.192.239:3306/street_light?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
    username: root
    password: Exc_led20200305
    type: com.alibaba.druid.pool.DruidDataSource
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #去掉控制台打印版本号
    banner: false
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  # 指定需要使用的日志配置文件名称
  config: classpath:logback-dev.xml
http:
  # 智慧照明
  sl:
#    url: http://129.204.254.98:60020
    url: http://129.204.254.98:60020
    deviceAll: /api/sl/lamp/device/all
    devicePage: /api/sl/lamp/device/page
    deviceById: /api/sl/lamp/device/
    pulldownByLampPostIdList: /api/sl/lamp/device/pulldown/by/lamp/post
    control: /api/sl/lamp/device/control
  # 公共WIFI
  wifi:
    url: http://129.204.254.98:60021
    deviceAll: /api/wifi/wifi/ap/device/all
    devicePage: /api/wifi/wifi/ap/device/list
    deviceById: /api/wifi/wifi/ap/device/get/
    pulldownByLampPostIdList: /api/wifi/wifi/ap/device/pulldown/by/lamp/post
  # 公共广播
  pb:
    url: http://129.204.254.98:60022
    deviceAll: /api/pb/radio/device/all
    devicePage: /api/pb/radio/device/getList
    deviceById: /api/pb/radio/device/
    pulldownByLampPostIdList: /api/pb/radio/device/pulldown/by/lamp/post
  # 智能安防
  ss:
#    url: http://192.168.111.89:60023
    url: http://129.204.254.98:60023
    deviceAll: /api/ss/ss/device/all
    devicePage: /api/ss/ss/device/page
    deviceById: /api/ss/ss/device/
    pulldownByLampPostIdList: /api/ss/ss/device/pulldown/by/lamp/post
  # 信息发布
  ir:
    url: http://129.204.254.98:60024
    deviceAll: /api/ir/screen/device/all
    devicePage: /api/ir/screen/device/query
    deviceById: /api/ir/screen/device/
    pulldownByLampPostIdList: /api/ir/screen/device/pulldown/by/lamp/post
  # 一键呼叫
  occ:
#    url: http://192.168.111.84:60025
    url: http://129.204.186.242:60025
    deviceAll: /api/occ/ah/device/all
    devicePage: /api/occ/ah/device/page
    deviceById: /api/occ/ah/device/
    pulldownByLampPostIdList: /api/occ/ah/device/pulldown/by/lamp/post
  # 环境监测
  em:
    url: http://129.204.254.98:60026
    deviceAll: /api/em/meteorological/device/all
    devicePage: /api/em/meteorological/device/getList
    deviceById: /api/em/meteorological/device/
    pulldownByLampPostIdList: /api/em/meteorological/device/pulldown/by/lamp/post
  # 运维管理
  woa:
    url: http://129.204.254.98:60029
    modifyByArea: /api/ua/user/modify/by/area
    user: /api/ua/user


#认证中心
security:
  authe:
    url: http://129.204.254.98:60029/api/ua/authe
  authc:
    url: http://129.204.254.98:60029/api/ua/authc
exclude:
  #不需要认证
  authe:
    url: /api/test,/swagger-ui.html,/swagger-resources,/v2/api-docs,/webjars/springfox-swagger-ui/**,/swagger-resources/configuration/ui,/static/**,/error
  #不需要鉴权
  authc:
    url: /api/test,/swagger-ui.html,/swagger-resources,/v2/api-docs,/webjars/springfox-swagger-ui/**,/swagger-resources/configuration/ui,/static/**,/error
