
package com.exc.street.light.wifi.webservice.online;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OnlineUserService", targetNamespace = "http://endpoint.webservice.smp.ruijie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnlineUserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineUsers", targetNamespace = "http://endpoint.webservice.smp.ruijie.com/", className = "com.exc.street.light.wifi.webservice.online.QueryOnlineUsers")
    @ResponseWrapper(localName = "queryOnlineUsersResponse", targetNamespace = "http://endpoint.webservice.smp.ruijie.com/", className = "com.exc.street.light.wifi.webservice.online.QueryOnlineUsersResponse")
    public String queryOnlineUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
