# 配置端口
server:
  port: 60032
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.111.89:3306/street_light_3.0?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
    username: root
    password: Exc_led1
    type: com.alibaba.druid.pool.DruidDataSource
  kafka:
    bootstrap-servers: 192.168.111.148:9092
    #生产者
    producer:
      #失败重试次数
      retries: 1
      #缓存大小，默认16k,配合properties中的linger使用
      batch-size: 16384
      #缓存消息的缓冲区大小，默认32，多分区使用时适当加大
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.exc.street.light.ed.serializer.PersonSerializer
      properties:
        linger.ms: 1
      acks: 1
    #消费者
    consumer:
      #偏移量提交方式: false 手动 true 自动，但是此处是交给spring自动处理的意思
      enable-auto-commit: false
      #偏移量自动提交间隔 commit为false时无效，spring处理有效
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: com.exc.street.light.ed.serializer.PersonDeSerializer
      properties:
        session.timeout.ms: 15000
    listener:
      type: batch
      concurrency: 3
      poll-timeout: 2000
      missingTopicsFatal: false
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为localhost）
    host: 192.168.111.165
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）为什么不能用 @exc123led123
    password: "@exc123led123"
    # redis连接超时时间（单位毫秒）
    timeout: 3000

kafka:
  topic:
    group-id: topicGroupId
  topic1:
    topic-name: websocket
kafka.client.topic: websocket1

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #去掉控制台打印版本号
    banner: false
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
 # 指定需要使用的日志配置文件名称
 config: classpath:logback-dev.xml

upload:
  path: D:/import/
  device:
    picture:
      path: D:/import/

http:
  # 智慧照明
  sl:
    url: http://192.168.112.17:60020
    deviceAll: /api/sl/lamp/device/all
    deviceById: /api/sl/lamp/device/
  # 公共WIFI
  wifi:
    url: http://192.168.112.252:60021
    deviceAll: /api/wifi/wifi/ap/device/all
    deviceById: /api/wifi/wifi/ap/device/
  # 公共广播
  pd:
    url: http://192.168.112.170:60022
    deviceAll: /api/pd/radio/device/all
    deviceById: /api/pd/radio/device/
  # 智能安防
  ss:
    url: http://192.168.112.104:60023
    deviceAll: /api/ss/ss/device/all
    deviceById: /api/ss/ss/device/
  # 信息发布
  ir:
    url: http://192.168.112.29:60024
    deviceAll: /api/ir/screen/device/all
    deviceById: /api/ir/screen/device/
  # 一键呼叫
  occ:
    url: http://192.168.112.104:60025
    deviceAll: /api/occ/ah/device/all
    deviceById: /api/occ/ah/device/
  # 环境监测
  em:
    url: http://192.168.111.170:60026
    deviceAll: /api/sl/lamp/device/all
    deviceById: /api/sl/lamp/device/

  # 设备位置管理
  dlm:
    url: http://192.168.112.29:60027
    deviceAll: /api/dlm/sl/lamp/post/all
    deviceById: /api/dlm/sl/lamp/post/device/
    lampPostById: /api/dlm/sl/lamp/post/

redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为localhost）
    host: 192.168.111.165
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）为什么不能用 @exc123led123
    password: "@exc123led123"
    # redis连接超时时间（单位毫秒）
    timeout: 3000

#认证中心
security:
  authe:
    url: http://192.168.112.252:60029/api/ua/authe
  authc:
    url: http://192.168.112.252:60029/api/ua/authc

#不需要认证
exclude:
  authe:
    url: /api/test,/error,/api/ed/ed/ashcan/gcReceive,/swagger-resources/**,/v2/api-docs,/doc.html,/webjars/**
  #不需要鉴权
  authc:
    url: /api/test,/error,/api/ed/ed/ashcan/gcReceive,/swagger-resources/**,/v2/api-docs,/doc.html,/webjars/**

# 井盖mqtt服务配置
mqtt:
  username: admin
  password: password
  host: tcp://iot.starwsn.com:1883
  topic[0]: /EXC/TL1/N110E/update
  topic[1]: /EXC/TL1/C110E/update
  qos[0]: 1
  qos[1]: 1
  clientId: excc-mqtt-test-1357912
  timeout: 10
  keepAlive: 20
  apikey: 5c2840d1e25a4168866d9ee944ff8758
